NPM packages repo set up
adcaptcha-org/adCAPTCHA-NPM-Packages pull request #1
Opened 2024-02-20 13:21 UTC by Lucasarenaterry

2024-03-06 17:17 UTC, orssich requested changes

2024-03-06 17:17 UTC, orssich commented on packages/node/README.md
> +  const response = await verify(apiKey, token)
Could do with more docs on what is in the return object

2024-03-06 17:17 UTC, orssich commented on packages/node/src/index.ts
> +export { verify } from './verify';
new line

2024-03-06 17:17 UTC, orssich commented on packages/node/tsconfig.json
> +}
new line

2024-03-06 17:17 UTC, orssich commented on packages/react/.babelrc
> +}
new line

2024-03-06 17:17 UTC, orssich commented on packages/react/jest.config.js
> +};
new line

2024-03-06 17:17 UTC, orssich commented on packages/react/src/util.ts
> +}
new line

2024-03-06 17:17 UTC, orssich commented on packages/react/test/adCAPTCHA.spec.tsx
> +});
new line

2024-03-06 17:17 UTC, orssich commented on packages/react/tsconfig.json
> +}
new line

2024-03-06 17:17 UTC, orssich commented on packages/react/tsup.config.ts
> +});
new line

2024-03-06 17:17 UTC, orssich commented on packages/react/README.md
> +# adCAPTCHA React
To the uninitiated it's not really clear what this component is doing - some explanation would be good

2024-03-06 17:17 UTC, orssich commented on packages/node/README.md
> +This package provides a Node component for adCAPTCHA.
More explanation of what this is actually providing. If it's verifying  success token then explain that

2024-03-06 17:17 UTC, orssich commented on packages/node/README.md
> +  const response = await verify(apiKey, token)
What is `apiKey`, where does it come from? tell the reader! Perhaps give example

Same for `token`

2024-03-07 08:53 UTC, orssich requested changes

2024-03-07 08:53 UTC, orssich commented on packages/react/README.md
> +# adCAPTCHA React
I still think you need to clarify what is happening here. This component does all the following:

- Show a captcha
- on success it gets a token (tell them what to with with it)

Some other things worth covering/examples:

- what happens on a failure
- callback examples as mentioned [here](https://docs.adcaptcha.com/callbacks)

Put yourself in the shoes of a rushed developer who just wants clear instructions/examples of what to do so they can just copy paste it

2024-03-07 10:45 UTC, MattGibney approved these changes

2024-03-07 10:49 UTC, orssich approved these changes

2024-03-07 10:50 UTC, merged