Adc 595 svelte integration
adcaptcha-org/adCAPTCHA-NPM-Packages pull request #13
Opened 2024-11-18 10:11 UTC by vasswann

2024-12-03 10:07 UTC, Lucasarenaterry requested changes

2024-12-03 10:07 UTC, Lucasarenaterry commented on README.md
> +### Captcha Integration
Change Captcha to adCAPTCHA

2024-12-03 10:07 UTC, Lucasarenaterry commented on README.md
>  ### Captcha Verification
and here

2024-12-03 10:07 UTC, Lucasarenaterry commented on examples/svelte/.env
> +VITE_SVELTE_APP_PLACEMENT_ID= ""
Could this be changed to be ADCAPTCHA_PLACEMENT_ID as to begin with I though this env for for svelte instead of the trigger.

2024-12-03 10:07 UTC, Lucasarenaterry commented on packages/svelte/.env
> +PUBLIC_SVELTE_APP_PLACEMENT_ID= your-placement-id
Same here to change it to ADCAPTCHA_PLACEMENT_ID

2024-12-03 10:07 UTC, Lucasarenaterry commented on packages/svelte/src/lib/adCAPTCHA.svelte
> +  <div data-adcaptcha={placementID}></div>
Add empty line at the end

2024-12-03 10:07 UTC, Lucasarenaterry commented on packages/svelte/src/lib/util.ts
> +  }
same here

2024-12-03 10:07 UTC, Lucasarenaterry commented on packages/svelte/tests/adCAPTCHA.test.ts
> +describe('adCaptcha testing components', () => {
typo: can you make sure adCaptcha are changed to adCAPTCHA

2024-12-03 10:07 UTC, Lucasarenaterry commented on packages/svelte/tests/adCAPTCHA.test.ts
> +});
empty line

2024-12-03 10:07 UTC, Lucasarenaterry commented on packages/svelte/tests/setup.ts
> +};
same here

2024-12-03 10:29 UTC, vasswann commented on packages/svelte/.env
> +PUBLIC_SVELTE_APP_PLACEMENT_ID= your-placement-id
I change this to PUBLIC_ADCAPTCHA_PLACEMENT_ID. Has to start with public

2024-12-03 10:29 UTC, vasswann commented on examples/svelte/.env
> +VITE_SVELTE_APP_PLACEMENT_ID= ""
This is has to start with VITE_ ADCAPTCHA_PLACEMENT_ID

2024-12-03 10:57 UTC, Lucasarenaterry approved these changes

2024-12-06 08:16 UTC, MattGibney approved these changes

2024-12-18 16:36 UTC, merged